# Generated by Django 4.1.3 on 2022-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0043_cashbook_like_count_cashbook_post_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_content',
        ),
        migrations.RemoveField(
            model_name='cashbook',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='cashbook',
            name='hashtags_count',
            field=models.PositiveIntegerField(null=True, verbose_name='해시태그수'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='tagging',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='cashbookapp.tag'),
        ),
    ]
